version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: iaio-opensearch-node1
    expose:
      - "9200"

  flask:
    image: iaio-flask
    container_name: iaio-flask
    environment:
      OPENSEARCH_HOSTNAME: opensearch-node1
    expose:
      - "5235"

  pm-manager:
    image: iaio-pm-manager
    container_name: iaio-pm-manager
    environment:
      OPENSEARCH_HOSTNAME: opensearch-node1
