version: '3'
services:
  opensearch-node1:
    extends:
      file: docker-compose.dev.base.yml
      service: opensearch-node1

  opensearch-init:
    extends:
      file: docker-compose.dev.base.yml
      service: opensearch-init
    depends_on:
      - opensearch-node1

  flask:
    extends:
      file: docker-compose.dev.base.yml
      service: flask
    volumes:
      - iaio-pi-db-debug:/app/instance

  pm-manager:
    extends:
      file: docker-compose.dev.base.yml
      service: pm-manager
    volumes:
      - iaio-pi-db-debug:/app/instance

volumes:
  iaio-pi-db-debug:
  opensearch-data1-1-debug:

networks:
  backend-net-debug:
