version: '3'
services:
  opensearch-node1:
    extends:
      file: docker-compose.dev.yml
      service: opensearch-node1

  opensearch-init:
    extends:
      file: docker-compose.base.yml
      service: opensearch-init
    depends_on:
      - opensearch-node1
    image: iaio-opensearch-init:debug
    container_name: iaio-opensearch-init-debug
    build:
      context: ..
      dockerfile: ./docker-opensearch-init/Dockerfile.dev
    networks:
      - backend-net-debug
    volumes:
      - ..:/app
    command: "12 5"

  flask:
    extends:
      file: docker-compose.dev.yml
      service: flask
    volumes:
      - iaio-pi-db-debug:/app/instance

  pm-manager:
    extends:
      file: docker-compose.dev.yml
      service: pm-manager
    volumes:
      - iaio-pi-db-debug:/app/instance


volumes:
  iaio-pi-db-debug:
  opensearch-data1-1-debug:

networks:
  backend-net-debug:
