version: '3'
services:
# include web:
  web:
    image: iaio-flutter-web
    container_name: iaio-flutter-web
    build:
      context: ../frontend
      dockerfile: ./docker-nginx/Dockerfile.prod
    ports:
      - "${LOCAL_ADDR}:80"
    networks:
      - backend-net

# extends:
  opensearch-node1:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: opensearch-node1
    container_name: iaio-opensearch-node1-1

  opensearch-init:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: opensearch-init
    depends_on:
      - opensearch-node1

  flask:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: flask
    ports:
      - "127.0.0.1:${BACKEND_LOCAL_PORT}:5235"

  pm-manager:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: pm-manager

volumes:
  opensearch-data1-1:
  iaio-pi-db:

networks:
  backend-net:
