version: '3'
services:
# include web:
  web:
    image: iaio-flutter-web
    container_name: iaio-flutter-web
    build:
      context: ../frontend
      dockerfile: ./docker-nginx/Dockerfile.prod
    ports:
      - "${LOCAL_ADDR}:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - backend-net

# extends:
  opensearch-node1:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: opensearch-node1
    container_name: iaio-opensearch-node1-1

  opensearch-init:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: opensearch-init
    depends_on:
      - opensearch-node1

  flask:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: flask
    ports:
      - "127.0.0.1:${BACKEND_LOCAL_PORT}:5235"
    environment:
      GOAUTH_CLIENT_ID: ${GOAUTH_CLIENT_ID}
      GOAUTH_CLIENT_SECRET: ${GOAUTH_CLIENT_SECRET}

  pm-manager:
    extends:
        file: ../backend/docker-compose/docker-compose.prod.base.yml
        service: pm-manager
    environment:
      GOAUTH_CLIENT_ID: ${GOAUTH_CLIENT_ID}
      GOAUTH_CLIENT_SECRET: ${GOAUTH_CLIENT_SECRET}

volumes:
  opensearch-data1-1:
  iaio-pi-db:

networks:
  backend-net:
