FROM python:3.10.10-slim-buster

WORKDIR /pre-app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# mount code dir in docker-compose.yml
WORKDIR /app

RUN mkdir /entry
COPY opensearch/scripts/init-docker.sh /entry
RUN chmod +x /entry/init-docker.sh
ENTRYPOINT ["/entry/init-docker.sh"]
