FROM python:3.10.10-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir ./flask && mkdir ./plugins && mkdir ./opensearch

COPY flask/*.py ./flask/
COPY plugins/*.py ./plugins/
COPY opensearch/*.py ./opensearch/

COPY flask/scripts/flask-docker-prod.sh .
RUN chmod +x flask-docker-prod.sh
ENTRYPOINT ["./flask-docker-prod.sh"]
