FROM python:3.10.10-slim-buster

WORKDIR /pre-app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# mount code dir in docker-compose.yml
WORKDIR /app

RUN mkdir /entry
COPY flask/scripts/flask-docker-dev.sh /entry
RUN chmod +x /entry/flask-docker-dev.sh
ENTRYPOINT ["/entry/flask-docker-dev.sh"]
