FROM python:3.10.10-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir ./flask && mkdir -p ./plugin_management/plugins && mkdir ./opensearch

COPY flask/*.py ./flask/
COPY plugin_management/plugins/*.py ./plugin_management/plugins/
COPY opensearch/*.py ./opensearch/

COPY flask/scripts/flask-docker-dev.sh .
RUN chmod +x flask-docker-dev.sh
ENTRYPOINT ["./flask-docker-dev.sh"]
