FROM python:3.10.10-slim-buster

WORKDIR /pre-app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# mount code dir in docker-compose.yml
WORKDIR /app

RUN mkdir /entry
COPY plugin_management/scripts/manager-init-docker.sh /entry
RUN chmod +x /entry/manager-init-docker.sh
ENTRYPOINT ["/entry/manager-init-docker.sh"]
